FROM node:20.19.2-alpine

# Crear directorio de la aplicación
WORKDIR /usr/src/app

# Copiar archivos de configuración de dependencias
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Usar nodemon para desarrollo
RUN npm install -g nodemon

# Start the application
CMD ["npm", "run", "dev"]
